name: 'Jest action'
description: 'Install modules and run tests'
inputs:
  folder:  
      description: 'Folder of the test'
      required: true
  test:  
    description: 'Testfile'
    required: false
    default: 'test.js'
runs:
  using: "composite"
  steps: 
    - name: Install ${{ inputs.folder }}/${{ inputs.test }}
      run: |
        echo "::group::npm install"
        npm install --prefix ${{ inputs.folder }}/ 
        echo "::endgroup::"
      shell: bash
    - name: Run tests ${{ inputs.folder }}/${{ inputs.test }}
      run: |
        echo "::group::npm test"
        npm test --prefix ${{ inputs.folder }}/ -t ${{ inputs.test }}
        echo "::endgroup::"
      shell: bash