# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Tema 2 - Testing unitario y de integración

on:
  push:
    branches: 
      - master
    paths:
      - tema2/**
  pull_request:
    branches: 
      - master
    paths:
      - tema2/**
  workflow_dispatch:

jobs:

  tema-2:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: [17]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: spring-test-ejem1
        run: mvn -B test --file tema2/spring-test-ejem1/pom.xml
      - name: spring-test-ejem2
        run: mvn -B test --file tema2/spring-test-ejem3/pom.xml
      - name: spring-test-ejem3
        run: mvn -B test --file tema2/spring-test-ejem3/pom.xml
      - name: spring-test-ejem4
        run: mvn -B test --file tema2/spring-test-ejem4/pom.xml
      - name: spring-test-ejem5
        run: mvn -B test --file tema2/spring-test-ejem5/pom.xml
      - name: spring-test-ejer1_solucion
        run: mvn -B test --file tema2/spring-test-ejer1/pom.xml
      - name: spring-test-ejer2_solucion
        run: mvn -B test --file tema2/spring-test-ejer2_solucion/pom.xml
      - name: test-containers-ejem1
        run: mvn -B test --file tema2/test-containers-ejem1/pom.xml
      - name: test-containers-ejem2A
        run: mvn -B test --file tema2/test-containers-ejem2A/pom.xml
      - name: test-containers-ejem2C
        run: mvn -B test --file tema2/test-containers-ejem2C/pom.xml
      - name: quarkus-test-ejem1
        run: mvn -B test --file tema2/quarkus-test-ejem1/pom.xml
      - name: quarkus-test-ejem2
        run: mvn -B test --file tema2/quarkus-test-ejem2/pom.xml

