name: Tema 3 CI

on:
  push:
    branches: 
      - master
    paths:
      - tema3/**
  pull_request:
    branches: 
      - master
    paths:
      - tema3/**

jobs:

  tema-3:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: jest-ejem1
            file: calculadora1.test.js
          - name: jest-ejem1
            file: calculadora2.test.js

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install ${{ matrix.name }}/${{ matrix.file }}
        run: npm install --prefix tema3/${{ matrix.name }}/ -t ${{ matrix.file }}
      - name: Run tests ${{ matrix.name }}/${{ matrix.file }}
        run: npm test --prefix tema3/${{ matrix.name }}/ -t ${{ matrix.file }}