name: Tema 3 CI

on:
  push:
    branches: 
      - master
    paths:
      - tema3/**
  pull_request:
    branches: 
      - master
    paths:
      - tema3/**

jobs:

  tema-3:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - folder: jest-ejem1
            test: calculadora1.test.js
          - folder: jest-ejem1
            test: calculadora2.test.js

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run Jest
        uses: ./.github/actions/jest/
        with:
          folder: ${{ matrix.folder }}
          test: ${{ matrix.test }}
